[package]
name = "cc-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
regex = "1.11.1"
tokio = { version = "1.40.0", features = ["full"] }
tokio-pipe = "0.2.12"
